site_name: Paraxial.io Documentation
site_url: https://docs.paraxial.io
theme:
  name: material
nav:
- Home:
  - index.md
  - Paraxial.io: 
    - Free Tier FAQ: free_tier_faq.md
    - Slack App: slack_app.md
  - Ruby:
    - Getting Started: ruby/start.md
    - PHPAttackMiddleware: ruby/php_attack.md
    - Bot Defense: ruby/bot_defense.md
    - Code Scans: ruby/code_scans.md
    - Changelog: ruby/CHANGELOG.md
  - Elixir:
    - Getting Started: elixir/start.md
    - GitHub App: elixir/github_app.md
    - GitLab App: elixir/gitlab_app.md
    - User Manual: elixir/user_manual.md
    - Cloud IPs: elixir/cloud_ips.md
    - ban_ip/3 and PHPAttackPlug: elixir/ban_ip.md
    - Agent Guide: elixir/agent_guide.md
    - App Audit: elixir/app_audit.md
    - Bot Defense: elixir/bot_defense_setup.md
    - Code Scans: elixir/code_scans.md
    - Quick Install: elixir/install.md
    - Live View Bot Defense: elixir/live_view_bot_defense.md
    - Agent Internals: elixir/agent.md
    - Changelog: elixir/CHANGELOG.md

theme:
  name: material
  logo: paraxial.png
  favicon: parax_fav.ico
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.expand
  - navigation.top
  - navigation.path
  - search.highlight
  - search.suggest
  - toc.follow
  - toc.integrate
  palette:
    scheme: slate
    primary: black
    accent: violet
  palette:
    - media: "(prefers-color-scheme)"
      accent: violet
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: violet
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: violet
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
- search

extra:
  generator: false